
apiVersion: v1
kind: Service
metadata:
  name: hello-world-f461-svc
  labels:
    app: hello-world-f461
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: hello-world-f461
  type: LoadBalancer